<?php
// $Id$

/**
 * hook for ctools plugins, hook $MODULE_$TYPE
 */
function akamai_esi_esi_plugins() {
  return array(
    'akamai_esi' => array(
      'name' => 'Akamai',
      'block_handler' => array(
        'class' => 'akamai_esi_block',
        'path' => drupal_get_path('module', 'akamai_esi') .'/classes',
        'file' => 'akamai_esi_block.inc',
        'parent' => 'esi',
      ),
    ),
  );
}
